# This is a basic workflow to help you get started with Actions

name: Python scrapping MariadB Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Install & setup maria DB
      - name: Start MariaDB
        uses: getong/mariadb-action@v1.1

      - name: Fix MariaDB
        run: |
          sudo apt-get update
          sudo apt install libmariadb3 libmariadb-dev

      # Install python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # launch tests
      - name: Run pytest
        run: python -m pytest tests/test_scrapper

      # Generate badges for readMe
      - name: Generate badges
        run: curl https://img.shields.io/github/workflow/status/rpdev63/brief-cicd-githubonly/test?label=tests&logo=github&style=flat-square > tests.svg
